import spacy

from spacy.tokens import DocBin

# Generated by CaseTalk on 16/02/2023 13:10:35

# -------------------------------------------
#                     en                     
# -------------------------------------------
nlp = spacy.blank("en")
training_data = [
  ("studetn Peter Johnson", [
    (8, 5, "firstname"),
    (14, 7, "lastname"),
  ]),
  ("studetn Mary Blight", [
    (8, 4, "firstname"),
    (13, 6, "lastname"),
  ]),
  ("studetn Marco Wobben", [
    (8, 5, "firstname"),
    (14, 6, "lastname"),
  ]),
  ("Peter Johnson is a student.", [
    (0, 5, "firstname"),
    (6, 7, "lastname"),
  ]),
  ("Mary Blight is a student.", [
    (0, 4, "firstname"),
    (5, 6, "lastname"),
  ]),
  ("Marco Wobben is a student.", [
    (0, 5, "firstname"),
    (6, 6, "lastname"),
  ]),
  ("Peter Johnson lives in New York.", [
    (0, 5, "firstname"),
    (6, 7, "lastname"),
    (0, 13, "Student"),
    (36, 8, "city_name"),
    (36, 8, "City"),
  ]),
  ("Mary Blight lives in Amsterdam.", [
    (0, 4, "firstname"),
    (5, 6, "lastname"),
    (0, 11, "Student"),
    (32, 9, "city_name"),
    (32, 9, "City"),
  ]),
  ("Marco Wobben lives in Utrecht.", [
    (0, 5, "firstname"),
    (6, 6, "lastname"),
    (0, 12, "Student"),
    (34, 7, "city_name"),
    (34, 7, "City"),
  ]),
  ("S101 concerns the development of a magazine infomration system.", [
    (0, 4, "apprenticeship_code"),
    (0, 4, "Apprenticeship"),
    (18, 48, "description"),
  ]),
  ("S101 takes place in New York.", [
    (0, 4, "apprenticeship_code"),
    (0, 4, "Apprenticeship"),
    (24, 8, "city_name"),
    (24, 8, "City"),
  ]),
  ("Peter Johnson has as preference no. 1 S101.", [
    (0, 5, "firstname"),
    (6, 7, "lastname"),
    (0, 13, "Student"),
    (49, 1, "number"),
    (51, 4, "apprenticeship_code"),
    (51, 4, "Apprenticeship"),
  ]),
  ("Mary Blight has as preference no. 2 S101.", [
    (0, 4, "firstname"),
    (5, 6, "lastname"),
    (0, 11, "Student"),
    (45, 1, "number"),
    (47, 4, "apprenticeship_code"),
    (47, 4, "Apprenticeship"),
  ]),
  ("Peter Johnson has as preference no. 2 S105.", [
    (0, 5, "firstname"),
    (6, 7, "lastname"),
    (0, 13, "Student"),
    (49, 1, "number"),
    (51, 4, "apprenticeship_code"),
    (51, 4, "Apprenticeship"),
  ]),
  ("Peter Johnson has as preference no. 3 S209.", [
    (0, 5, "firstname"),
    (6, 7, "lastname"),
    (0, 13, "Student"),
    (49, 1, "number"),
    (51, 4, "apprenticeship_code"),
    (51, 4, "Apprenticeship"),
  ]),
  ("Mary Blight has as preference no. 1 S112.", [
    (0, 4, "firstname"),
    (5, 6, "lastname"),
    (0, 11, "Student"),
    (45, 1, "number"),
    (47, 4, "apprenticeship_code"),
    (47, 4, "Apprenticeship"),
  ]),
  ("S101 is assigned to Peter Johnson.", [
    (0, 4, "apprenticeship_code"),
    (0, 4, "Apprenticeship"),
    (24, 5, "firstname"),
    (30, 7, "lastname"),
    (24, 13, "Student"),
  ]),
  ("S209 is assigned to Mary Blight.", [
    (0, 4, "apprenticeship_code"),
    (0, 4, "Apprenticeship"),
    (24, 4, "firstname"),
    (29, 6, "lastname"),
    (24, 11, "Student"),
  ]),
  ("Mary Blight graduated on 2019-12-31.", [
    (0, 4, "firstname"),
    (5, 6, "lastname"),
    (0, 11, "Student"),
    (0, 11, "Graduate"),
    (47, 10, "date"),
  ]),
  ("Amsterdam has 400000 citizens.", [
    (0, 9, "city_name"),
    (0, 9, "City"),
    (23, 6, "#citizens"),
  ]),
  ("S101 will take 4 months.", [
    (0, 4, "apprenticeship_code"),
    (0, 4, "Apprenticeship"),
    (19, 1, "Month Amount"),
  ]),
  ("S101 falls in the ICT.", [
    (0, 4, "apprenticeship_code"),
    (0, 4, "Apprenticeship"),
    (22, 3, "Category Title"),
  ]),
  ("Marco Wobben receives mail atmainstreet1,Utrecht Zeeland The Netherlandss.", [
    (0, 5, "firstname"),
    (6, 6, "lastname"),
    (0, 12, "Student"),
    (41, 10, "Street"),
    (51, 1, "house number"),
    (41, 11, "street and number"),
    (64, 7, "city_name"),
    (64, 7, "City"),
    (79, 7, "Provence"),
    (87, 15, "Country"),
    (41, 43, "Address"),
  ]),
  ("Marco Wobben is a buddy for Mary Blight.", [
    (0, 5, "firstname"),
    (6, 6, "lastname"),
    (0, 12, "Student"),
    (40, 4, "firstname"),
    (45, 6, "lastname"),
    (40, 11, "Student"),
  ]),
  ("Mary Blight is a Graduate.", [
    (0, 4, "firstname"),
    (5, 6, "lastname"),
    (0, 11, "Student"),
    (28, 8, "Type"),
  ]),
  ("Marco Wobben is born on 1969-03-27.", [
    (0, 5, "firstname"),
    (6, 6, "lastname"),
    (0, 12, "Student"),
    (0, 12, "Person"),
    (48, 10, "Day"),
  ]),
  ("542 is born on 1984-11-21.", [
    (0, 3, "Emp_no"),
    (0, 3, "Employee"),
    (0, 3, "Person"),
    (21, 10, "Day"),
  ]),
]
db = DocBin()
for text, annotations in training_data:
  doc = nlp(text)
  ents = []
  for start, end, label in annotations:
      span = doc.char_span(start, end, label=label)
      ents.append(span)
  doc.ents = ents
  db.add(doc)
db.to_disk("\\Mac\Home\Documents\CaseTalk\Marketing\By Others\Han16juni2004\apprenticeship-en.spacy")


# -------------------------------------------
#                     nl                     
# -------------------------------------------
nlp = spacy.blank("nl")
training_data = [
  ("scholier Peter Johnson", [
    (9, 5, "firstname"),
    (15, 7, "lastname"),
  ]),
  ("scholier Mary Blight", [
    (9, 4, "firstname"),
    (14, 6, "lastname"),
  ]),
  ("scholier Marco Wobben", [
    (9, 5, "firstname"),
    (15, 6, "lastname"),
  ]),
  ("stage S101", [
    (6, 4, "apprenticeship_code"),
  ]),
  ("stage S102", [
    (6, 4, "apprenticeship_code"),
  ]),
  ("stage S105", [
    (6, 4, "apprenticeship_code"),
  ]),
  ("stage S209", [
    (6, 4, "apprenticeship_code"),
  ]),
  ("stage S112", [
    (6, 4, "apprenticeship_code"),
  ]),
  ("Peter Johnson woont in New York.", [
    (0, 5, "firstname"),
    (6, 7, "lastname"),
    (0, 13, "Student"),
    (36, 8, "city_name"),
    (36, 8, "City"),
  ]),
  ("Mary Blight woont in Amsterdam.", [
    (0, 4, "firstname"),
    (5, 6, "lastname"),
    (0, 11, "Student"),
    (32, 9, "city_name"),
    (32, 9, "City"),
  ]),
  ("Marco Wobben woont in Utrecht.", [
    (0, 5, "firstname"),
    (6, 6, "lastname"),
    (0, 12, "Student"),
    (34, 7, "city_name"),
    (34, 7, "City"),
  ]),
  ("Amsterdam heeft 400000 inwoners.", [
    (0, 9, "city_name"),
    (0, 9, "City"),
    (25, 6, "#citizens"),
  ]),
  ("Peter Johnson is een scholier.", [
    (0, 5, "firstname"),
    (6, 7, "lastname"),
  ]),
  ("Mary Blight is een scholier.", [
    (0, 4, "firstname"),
    (5, 6, "lastname"),
  ]),
  ("Marco Wobben is een scholier.", [
    (0, 5, "firstname"),
    (6, 6, "lastname"),
  ]),
  ("S101 vindt plaats in New York.", [
    (0, 4, "apprenticeship_code"),
    (0, 4, "Apprenticeship"),
    (25, 8, "city_name"),
    (25, 8, "City"),
  ]),
  ("S101 betreft the development of a magazine infomration system.", [
    (0, 4, "apprenticeship_code"),
    (0, 4, "Apprenticeship"),
    (17, 48, "description"),
  ]),
  ("Mary Blight studeerde af op 2019-12-31.", [
    (0, 4, "firstname"),
    (5, 6, "lastname"),
    (0, 11, "Student"),
    (0, 11, "Graduate"),
    (50, 10, "date"),
  ]),
  ("Peter Johnson heeft als voorkeur 1 de S101.", [
    (0, 5, "firstname"),
    (6, 7, "lastname"),
    (0, 13, "Student"),
    (46, 1, "number"),
    (51, 4, "apprenticeship_code"),
    (51, 4, "Apprenticeship"),
  ]),
  ("Mary Blight heeft als voorkeur 2 de S101.", [
    (0, 4, "firstname"),
    (5, 6, "lastname"),
    (0, 11, "Student"),
    (42, 1, "number"),
    (47, 4, "apprenticeship_code"),
    (47, 4, "Apprenticeship"),
  ]),
  ("Peter Johnson heeft als voorkeur 2 de S105.", [
    (0, 5, "firstname"),
    (6, 7, "lastname"),
    (0, 13, "Student"),
    (46, 1, "number"),
    (51, 4, "apprenticeship_code"),
    (51, 4, "Apprenticeship"),
  ]),
  ("Peter Johnson heeft als voorkeur 3 de S209.", [
    (0, 5, "firstname"),
    (6, 7, "lastname"),
    (0, 13, "Student"),
    (46, 1, "number"),
    (51, 4, "apprenticeship_code"),
    (51, 4, "Apprenticeship"),
  ]),
  ("Mary Blight heeft als voorkeur 1 de S112.", [
    (0, 4, "firstname"),
    (5, 6, "lastname"),
    (0, 11, "Student"),
    (42, 1, "number"),
    (47, 4, "apprenticeship_code"),
    (47, 4, "Apprenticeship"),
  ]),
]
db = DocBin()
for text, annotations in training_data:
  doc = nlp(text)
  ents = []
  for start, end, label in annotations:
      span = doc.char_span(start, end, label=label)
      ents.append(span)
  doc.ents = ents
  db.add(doc)
db.to_disk("\\Mac\Home\Documents\CaseTalk\Marketing\By Others\Han16juni2004\apprenticeship-nl.spacy")

